/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: plcontainer.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "plcontainer.pb-c.h"
void   plcontainer__proc_src__init
                     (Plcontainer__ProcSrc         *message)
{
  static const Plcontainer__ProcSrc init_value = PLCONTAINER__PROC_SRC__INIT;
  *message = init_value;
}
size_t plcontainer__proc_src__get_packed_size
                     (const Plcontainer__ProcSrc *message)
{
  assert(message->base.descriptor == &plcontainer__proc_src__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t plcontainer__proc_src__pack
                     (const Plcontainer__ProcSrc *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &plcontainer__proc_src__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t plcontainer__proc_src__pack_to_buffer
                     (const Plcontainer__ProcSrc *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &plcontainer__proc_src__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Plcontainer__ProcSrc *
       plcontainer__proc_src__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Plcontainer__ProcSrc *)
     protobuf_c_message_unpack (&plcontainer__proc_src__descriptor,
                                allocator, len, data);
}
void   plcontainer__proc_src__free_unpacked
                     (Plcontainer__ProcSrc *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &plcontainer__proc_src__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   plcontainer__plc_type__init
                     (Plcontainer__PlcType         *message)
{
  static const Plcontainer__PlcType init_value = PLCONTAINER__PLC_TYPE__INIT;
  *message = init_value;
}
size_t plcontainer__plc_type__get_packed_size
                     (const Plcontainer__PlcType *message)
{
  assert(message->base.descriptor == &plcontainer__plc_type__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t plcontainer__plc_type__pack
                     (const Plcontainer__PlcType *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &plcontainer__plc_type__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t plcontainer__plc_type__pack_to_buffer
                     (const Plcontainer__PlcType *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &plcontainer__plc_type__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Plcontainer__PlcType *
       plcontainer__plc_type__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Plcontainer__PlcType *)
     protobuf_c_message_unpack (&plcontainer__plc_type__descriptor,
                                allocator, len, data);
}
void   plcontainer__plc_type__free_unpacked
                     (Plcontainer__PlcType *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &plcontainer__plc_type__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   plcontainer__raw_data__init
                     (Plcontainer__RawData         *message)
{
  static const Plcontainer__RawData init_value = PLCONTAINER__RAW_DATA__INIT;
  *message = init_value;
}
size_t plcontainer__raw_data__get_packed_size
                     (const Plcontainer__RawData *message)
{
  assert(message->base.descriptor == &plcontainer__raw_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t plcontainer__raw_data__pack
                     (const Plcontainer__RawData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &plcontainer__raw_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t plcontainer__raw_data__pack_to_buffer
                     (const Plcontainer__RawData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &plcontainer__raw_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Plcontainer__RawData *
       plcontainer__raw_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Plcontainer__RawData *)
     protobuf_c_message_unpack (&plcontainer__raw_data__descriptor,
                                allocator, len, data);
}
void   plcontainer__raw_data__free_unpacked
                     (Plcontainer__RawData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &plcontainer__raw_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   plcontainer__argument__init
                     (Plcontainer__Argument         *message)
{
  static const Plcontainer__Argument init_value = PLCONTAINER__ARGUMENT__INIT;
  *message = init_value;
}
size_t plcontainer__argument__get_packed_size
                     (const Plcontainer__Argument *message)
{
  assert(message->base.descriptor == &plcontainer__argument__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t plcontainer__argument__pack
                     (const Plcontainer__Argument *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &plcontainer__argument__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t plcontainer__argument__pack_to_buffer
                     (const Plcontainer__Argument *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &plcontainer__argument__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Plcontainer__Argument *
       plcontainer__argument__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Plcontainer__Argument *)
     protobuf_c_message_unpack (&plcontainer__argument__descriptor,
                                allocator, len, data);
}
void   plcontainer__argument__free_unpacked
                     (Plcontainer__Argument *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &plcontainer__argument__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   plcontainer__header__init
                     (Plcontainer__Header         *message)
{
  static const Plcontainer__Header init_value = PLCONTAINER__HEADER__INIT;
  *message = init_value;
}
size_t plcontainer__header__get_packed_size
                     (const Plcontainer__Header *message)
{
  assert(message->base.descriptor == &plcontainer__header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t plcontainer__header__pack
                     (const Plcontainer__Header *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &plcontainer__header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t plcontainer__header__pack_to_buffer
                     (const Plcontainer__Header *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &plcontainer__header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Plcontainer__Header *
       plcontainer__header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Plcontainer__Header *)
     protobuf_c_message_unpack (&plcontainer__header__descriptor,
                                allocator, len, data);
}
void   plcontainer__header__free_unpacked
                     (Plcontainer__Header *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &plcontainer__header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   plcontainer__ping__init
                     (Plcontainer__Ping         *message)
{
  static const Plcontainer__Ping init_value = PLCONTAINER__PING__INIT;
  *message = init_value;
}
size_t plcontainer__ping__get_packed_size
                     (const Plcontainer__Ping *message)
{
  assert(message->base.descriptor == &plcontainer__ping__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t plcontainer__ping__pack
                     (const Plcontainer__Ping *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &plcontainer__ping__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t plcontainer__ping__pack_to_buffer
                     (const Plcontainer__Ping *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &plcontainer__ping__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Plcontainer__Ping *
       plcontainer__ping__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Plcontainer__Ping *)
     protobuf_c_message_unpack (&plcontainer__ping__descriptor,
                                allocator, len, data);
}
void   plcontainer__ping__free_unpacked
                     (Plcontainer__Ping *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &plcontainer__ping__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   plcontainer__error__init
                     (Plcontainer__Error         *message)
{
  static const Plcontainer__Error init_value = PLCONTAINER__ERROR__INIT;
  *message = init_value;
}
size_t plcontainer__error__get_packed_size
                     (const Plcontainer__Error *message)
{
  assert(message->base.descriptor == &plcontainer__error__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t plcontainer__error__pack
                     (const Plcontainer__Error *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &plcontainer__error__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t plcontainer__error__pack_to_buffer
                     (const Plcontainer__Error *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &plcontainer__error__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Plcontainer__Error *
       plcontainer__error__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Plcontainer__Error *)
     protobuf_c_message_unpack (&plcontainer__error__descriptor,
                                allocator, len, data);
}
void   plcontainer__error__free_unpacked
                     (Plcontainer__Error *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &plcontainer__error__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   plcontainer__call_request__init
                     (Plcontainer__CallRequest         *message)
{
  static const Plcontainer__CallRequest init_value = PLCONTAINER__CALL_REQUEST__INIT;
  *message = init_value;
}
size_t plcontainer__call_request__get_packed_size
                     (const Plcontainer__CallRequest *message)
{
  assert(message->base.descriptor == &plcontainer__call_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t plcontainer__call_request__pack
                     (const Plcontainer__CallRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &plcontainer__call_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t plcontainer__call_request__pack_to_buffer
                     (const Plcontainer__CallRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &plcontainer__call_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Plcontainer__CallRequest *
       plcontainer__call_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Plcontainer__CallRequest *)
     protobuf_c_message_unpack (&plcontainer__call_request__descriptor,
                                allocator, len, data);
}
void   plcontainer__call_request__free_unpacked
                     (Plcontainer__CallRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &plcontainer__call_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   plcontainer__result__init
                     (Plcontainer__Result         *message)
{
  static const Plcontainer__Result init_value = PLCONTAINER__RESULT__INIT;
  *message = init_value;
}
size_t plcontainer__result__get_packed_size
                     (const Plcontainer__Result *message)
{
  assert(message->base.descriptor == &plcontainer__result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t plcontainer__result__pack
                     (const Plcontainer__Result *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &plcontainer__result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t plcontainer__result__pack_to_buffer
                     (const Plcontainer__Result *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &plcontainer__result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Plcontainer__Result *
       plcontainer__result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Plcontainer__Result *)
     protobuf_c_message_unpack (&plcontainer__result__descriptor,
                                allocator, len, data);
}
void   plcontainer__result__free_unpacked
                     (Plcontainer__Result *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &plcontainer__result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   plcontainer__log__init
                     (Plcontainer__Log         *message)
{
  static const Plcontainer__Log init_value = PLCONTAINER__LOG__INIT;
  *message = init_value;
}
size_t plcontainer__log__get_packed_size
                     (const Plcontainer__Log *message)
{
  assert(message->base.descriptor == &plcontainer__log__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t plcontainer__log__pack
                     (const Plcontainer__Log *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &plcontainer__log__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t plcontainer__log__pack_to_buffer
                     (const Plcontainer__Log *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &plcontainer__log__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Plcontainer__Log *
       plcontainer__log__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Plcontainer__Log *)
     protobuf_c_message_unpack (&plcontainer__log__descriptor,
                                allocator, len, data);
}
void   plcontainer__log__free_unpacked
                     (Plcontainer__Log *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &plcontainer__log__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   plcontainer__quote__init
                     (Plcontainer__Quote         *message)
{
  static const Plcontainer__Quote init_value = PLCONTAINER__QUOTE__INIT;
  *message = init_value;
}
size_t plcontainer__quote__get_packed_size
                     (const Plcontainer__Quote *message)
{
  assert(message->base.descriptor == &plcontainer__quote__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t plcontainer__quote__pack
                     (const Plcontainer__Quote *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &plcontainer__quote__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t plcontainer__quote__pack_to_buffer
                     (const Plcontainer__Quote *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &plcontainer__quote__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Plcontainer__Quote *
       plcontainer__quote__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Plcontainer__Quote *)
     protobuf_c_message_unpack (&plcontainer__quote__descriptor,
                                allocator, len, data);
}
void   plcontainer__quote__free_unpacked
                     (Plcontainer__Quote *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &plcontainer__quote__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   plcontainer__quote_result__init
                     (Plcontainer__QuoteResult         *message)
{
  static const Plcontainer__QuoteResult init_value = PLCONTAINER__QUOTE_RESULT__INIT;
  *message = init_value;
}
size_t plcontainer__quote_result__get_packed_size
                     (const Plcontainer__QuoteResult *message)
{
  assert(message->base.descriptor == &plcontainer__quote_result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t plcontainer__quote_result__pack
                     (const Plcontainer__QuoteResult *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &plcontainer__quote_result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t plcontainer__quote_result__pack_to_buffer
                     (const Plcontainer__QuoteResult *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &plcontainer__quote_result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Plcontainer__QuoteResult *
       plcontainer__quote_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Plcontainer__QuoteResult *)
     protobuf_c_message_unpack (&plcontainer__quote_result__descriptor,
                                allocator, len, data);
}
void   plcontainer__quote_result__free_unpacked
                     (Plcontainer__QuoteResult *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &plcontainer__quote_result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   plcontainer__sql__init
                     (Plcontainer__SQL         *message)
{
  static const Plcontainer__SQL init_value = PLCONTAINER__SQL__INIT;
  *message = init_value;
}
size_t plcontainer__sql__get_packed_size
                     (const Plcontainer__SQL *message)
{
  assert(message->base.descriptor == &plcontainer__sql__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t plcontainer__sql__pack
                     (const Plcontainer__SQL *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &plcontainer__sql__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t plcontainer__sql__pack_to_buffer
                     (const Plcontainer__SQL *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &plcontainer__sql__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Plcontainer__SQL *
       plcontainer__sql__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Plcontainer__SQL *)
     protobuf_c_message_unpack (&plcontainer__sql__descriptor,
                                allocator, len, data);
}
void   plcontainer__sql__free_unpacked
                     (Plcontainer__SQL *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &plcontainer__sql__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   plcontainer__raw__init
                     (Plcontainer__Raw         *message)
{
  static const Plcontainer__Raw init_value = PLCONTAINER__RAW__INIT;
  *message = init_value;
}
size_t plcontainer__raw__get_packed_size
                     (const Plcontainer__Raw *message)
{
  assert(message->base.descriptor == &plcontainer__raw__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t plcontainer__raw__pack
                     (const Plcontainer__Raw *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &plcontainer__raw__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t plcontainer__raw__pack_to_buffer
                     (const Plcontainer__Raw *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &plcontainer__raw__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Plcontainer__Raw *
       plcontainer__raw__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Plcontainer__Raw *)
     protobuf_c_message_unpack (&plcontainer__raw__descriptor,
                                allocator, len, data);
}
void   plcontainer__raw__free_unpacked
                     (Plcontainer__Raw *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &plcontainer__raw__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   plcontainer__subtransaction__init
                     (Plcontainer__Subtransaction         *message)
{
  static const Plcontainer__Subtransaction init_value = PLCONTAINER__SUBTRANSACTION__INIT;
  *message = init_value;
}
size_t plcontainer__subtransaction__get_packed_size
                     (const Plcontainer__Subtransaction *message)
{
  assert(message->base.descriptor == &plcontainer__subtransaction__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t plcontainer__subtransaction__pack
                     (const Plcontainer__Subtransaction *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &plcontainer__subtransaction__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t plcontainer__subtransaction__pack_to_buffer
                     (const Plcontainer__Subtransaction *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &plcontainer__subtransaction__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Plcontainer__Subtransaction *
       plcontainer__subtransaction__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Plcontainer__Subtransaction *)
     protobuf_c_message_unpack (&plcontainer__subtransaction__descriptor,
                                allocator, len, data);
}
void   plcontainer__subtransaction__free_unpacked
                     (Plcontainer__Subtransaction *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &plcontainer__subtransaction__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   plcontainer__subtransaction_result__init
                     (Plcontainer__SubtransactionResult         *message)
{
  static const Plcontainer__SubtransactionResult init_value = PLCONTAINER__SUBTRANSACTION_RESULT__INIT;
  *message = init_value;
}
size_t plcontainer__subtransaction_result__get_packed_size
                     (const Plcontainer__SubtransactionResult *message)
{
  assert(message->base.descriptor == &plcontainer__subtransaction_result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t plcontainer__subtransaction_result__pack
                     (const Plcontainer__SubtransactionResult *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &plcontainer__subtransaction_result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t plcontainer__subtransaction_result__pack_to_buffer
                     (const Plcontainer__SubtransactionResult *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &plcontainer__subtransaction_result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Plcontainer__SubtransactionResult *
       plcontainer__subtransaction_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Plcontainer__SubtransactionResult *)
     protobuf_c_message_unpack (&plcontainer__subtransaction_result__descriptor,
                                allocator, len, data);
}
void   plcontainer__subtransaction_result__free_unpacked
                     (Plcontainer__SubtransactionResult *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &plcontainer__subtransaction_result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor plcontainer__proc_src__field_descriptors[2] =
{
  {
    "src",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Plcontainer__ProcSrc, src),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Plcontainer__ProcSrc, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned plcontainer__proc_src__field_indices_by_name[] = {
  1,   /* field[1] = name */
  0,   /* field[0] = src */
};
static const ProtobufCIntRange plcontainer__proc_src__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor plcontainer__proc_src__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "plcontainer.ProcSrc",
  "ProcSrc",
  "Plcontainer__ProcSrc",
  "plcontainer",
  sizeof(Plcontainer__ProcSrc),
  2,
  plcontainer__proc_src__field_descriptors,
  plcontainer__proc_src__field_indices_by_name,
  1,  plcontainer__proc_src__number_ranges,
  (ProtobufCMessageInit) plcontainer__proc_src__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor plcontainer__plc_type__field_descriptors[4] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Plcontainer__PlcType, type),
    &plcontainer__data_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nSubTypes",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Plcontainer__PlcType, nsubtypes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "typeName",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Plcontainer__PlcType, typename_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "subTypes",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Plcontainer__PlcType, subtypes),
    &plcontainer__plc_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned plcontainer__plc_type__field_indices_by_name[] = {
  1,   /* field[1] = nSubTypes */
  3,   /* field[3] = subTypes */
  0,   /* field[0] = type */
  2,   /* field[2] = typeName */
};
static const ProtobufCIntRange plcontainer__plc_type__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor plcontainer__plc_type__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "plcontainer.PlcType",
  "PlcType",
  "Plcontainer__PlcType",
  "plcontainer",
  sizeof(Plcontainer__PlcType),
  4,
  plcontainer__plc_type__field_descriptors,
  plcontainer__plc_type__field_indices_by_name,
  1,  plcontainer__plc_type__number_ranges,
  (ProtobufCMessageInit) plcontainer__plc_type__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor plcontainer__raw_data__field_descriptors[2] =
{
  {
    "isnull",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Plcontainer__RawData, isnull),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Plcontainer__RawData, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned plcontainer__raw_data__field_indices_by_name[] = {
  0,   /* field[0] = isnull */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange plcontainer__raw_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor plcontainer__raw_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "plcontainer.RawData",
  "RawData",
  "Plcontainer__RawData",
  "plcontainer",
  sizeof(Plcontainer__RawData),
  2,
  plcontainer__raw_data__field_descriptors,
  plcontainer__raw_data__field_indices_by_name,
  1,  plcontainer__raw_data__number_ranges,
  (ProtobufCMessageInit) plcontainer__raw_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor plcontainer__argument__field_descriptors[3] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Plcontainer__Argument, type),
    &plcontainer__plc_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Plcontainer__Argument, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Plcontainer__Argument, data),
    &plcontainer__raw_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned plcontainer__argument__field_indices_by_name[] = {
  2,   /* field[2] = data */
  1,   /* field[1] = name */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange plcontainer__argument__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor plcontainer__argument__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "plcontainer.Argument",
  "Argument",
  "Plcontainer__Argument",
  "plcontainer",
  sizeof(Plcontainer__Argument),
  3,
  plcontainer__argument__field_descriptors,
  plcontainer__argument__field_indices_by_name,
  1,  plcontainer__argument__number_ranges,
  (ProtobufCMessageInit) plcontainer__argument__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor plcontainer__header__field_descriptors[2] =
{
  {
    "message_type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Plcontainer__Header, message_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message_length",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Plcontainer__Header, message_length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned plcontainer__header__field_indices_by_name[] = {
  1,   /* field[1] = message_length */
  0,   /* field[0] = message_type */
};
static const ProtobufCIntRange plcontainer__header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor plcontainer__header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "plcontainer.Header",
  "Header",
  "Plcontainer__Header",
  "plcontainer",
  sizeof(Plcontainer__Header),
  2,
  plcontainer__header__field_descriptors,
  plcontainer__header__field_indices_by_name,
  1,  plcontainer__header__number_ranges,
  (ProtobufCMessageInit) plcontainer__header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor plcontainer__ping__field_descriptors[1] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Plcontainer__Ping, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned plcontainer__ping__field_indices_by_name[] = {
  0,   /* field[0] = version */
};
static const ProtobufCIntRange plcontainer__ping__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor plcontainer__ping__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "plcontainer.Ping",
  "Ping",
  "Plcontainer__Ping",
  "plcontainer",
  sizeof(Plcontainer__Ping),
  1,
  plcontainer__ping__field_descriptors,
  plcontainer__ping__field_indices_by_name,
  1,  plcontainer__ping__number_ranges,
  (ProtobufCMessageInit) plcontainer__ping__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor plcontainer__error__field_descriptors[2] =
{
  {
    "message",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Plcontainer__Error, message),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stacktrace",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Plcontainer__Error, stacktrace),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned plcontainer__error__field_indices_by_name[] = {
  0,   /* field[0] = message */
  1,   /* field[1] = stacktrace */
};
static const ProtobufCIntRange plcontainer__error__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor plcontainer__error__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "plcontainer.Error",
  "Error",
  "Plcontainer__Error",
  "plcontainer",
  sizeof(Plcontainer__Error),
  2,
  plcontainer__error__field_descriptors,
  plcontainer__error__field_indices_by_name,
  1,  plcontainer__error__number_ranges,
  (ProtobufCMessageInit) plcontainer__error__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor plcontainer__call_request__field_descriptors[9] =
{
  {
    "objectid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Plcontainer__CallRequest, objectid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hasChanged",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Plcontainer__CallRequest, haschanged),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proc",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Plcontainer__CallRequest, proc),
    &plcontainer__proc_src__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "logLevel",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Plcontainer__CallRequest, loglevel),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "retType",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Plcontainer__CallRequest, rettype),
    &plcontainer__plc_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "retset",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Plcontainer__CallRequest, retset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nargs",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Plcontainer__CallRequest, nargs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "serverenc",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Plcontainer__CallRequest, serverenc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "args",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Plcontainer__CallRequest, n_args),
    offsetof(Plcontainer__CallRequest, args),
    &plcontainer__argument__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned plcontainer__call_request__field_indices_by_name[] = {
  8,   /* field[8] = args */
  1,   /* field[1] = hasChanged */
  3,   /* field[3] = logLevel */
  6,   /* field[6] = nargs */
  0,   /* field[0] = objectid */
  2,   /* field[2] = proc */
  4,   /* field[4] = retType */
  5,   /* field[5] = retset */
  7,   /* field[7] = serverenc */
};
static const ProtobufCIntRange plcontainer__call_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor plcontainer__call_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "plcontainer.CallRequest",
  "CallRequest",
  "Plcontainer__CallRequest",
  "plcontainer",
  sizeof(Plcontainer__CallRequest),
  9,
  plcontainer__call_request__field_descriptors,
  plcontainer__call_request__field_indices_by_name,
  1,  plcontainer__call_request__number_ranges,
  (ProtobufCMessageInit) plcontainer__call_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor plcontainer__result__field_descriptors[6] =
{
  {
    "rows",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Plcontainer__Result, rows),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cols",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Plcontainer__Result, cols),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "types",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Plcontainer__Result, n_types),
    offsetof(Plcontainer__Result, types),
    &plcontainer__plc_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "names",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Plcontainer__Result, n_names),
    offsetof(Plcontainer__Result, names),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Plcontainer__Result, n_data),
    offsetof(Plcontainer__Result, data),
    &plcontainer__raw_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "exception",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Plcontainer__Result, exception),
    &plcontainer__error__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned plcontainer__result__field_indices_by_name[] = {
  1,   /* field[1] = cols */
  4,   /* field[4] = data */
  5,   /* field[5] = exception */
  3,   /* field[3] = names */
  0,   /* field[0] = rows */
  2,   /* field[2] = types */
};
static const ProtobufCIntRange plcontainer__result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor plcontainer__result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "plcontainer.Result",
  "Result",
  "Plcontainer__Result",
  "plcontainer",
  sizeof(Plcontainer__Result),
  6,
  plcontainer__result__field_descriptors,
  plcontainer__result__field_indices_by_name,
  1,  plcontainer__result__number_ranges,
  (ProtobufCMessageInit) plcontainer__result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor plcontainer__log__field_descriptors[2] =
{
  {
    "level",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Plcontainer__Log, level),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Plcontainer__Log, message),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned plcontainer__log__field_indices_by_name[] = {
  0,   /* field[0] = level */
  1,   /* field[1] = message */
};
static const ProtobufCIntRange plcontainer__log__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor plcontainer__log__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "plcontainer.Log",
  "Log",
  "Plcontainer__Log",
  "plcontainer",
  sizeof(Plcontainer__Log),
  2,
  plcontainer__log__field_descriptors,
  plcontainer__log__field_indices_by_name,
  1,  plcontainer__log__number_ranges,
  (ProtobufCMessageInit) plcontainer__log__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor plcontainer__quote__field_descriptors[2] =
{
  {
    "quote_type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Plcontainer__Quote, quote_type),
    &plcontainer__quote_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Plcontainer__Quote, msg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned plcontainer__quote__field_indices_by_name[] = {
  1,   /* field[1] = msg */
  0,   /* field[0] = quote_type */
};
static const ProtobufCIntRange plcontainer__quote__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor plcontainer__quote__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "plcontainer.Quote",
  "Quote",
  "Plcontainer__Quote",
  "plcontainer",
  sizeof(Plcontainer__Quote),
  2,
  plcontainer__quote__field_descriptors,
  plcontainer__quote__field_indices_by_name,
  1,  plcontainer__quote__number_ranges,
  (ProtobufCMessageInit) plcontainer__quote__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor plcontainer__quote_result__field_descriptors[2] =
{
  {
    "quote_type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Plcontainer__QuoteResult, quote_type),
    &plcontainer__quote_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "result",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Plcontainer__QuoteResult, result),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned plcontainer__quote_result__field_indices_by_name[] = {
  0,   /* field[0] = quote_type */
  1,   /* field[1] = result */
};
static const ProtobufCIntRange plcontainer__quote_result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor plcontainer__quote_result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "plcontainer.QuoteResult",
  "QuoteResult",
  "Plcontainer__QuoteResult",
  "plcontainer",
  sizeof(Plcontainer__QuoteResult),
  2,
  plcontainer__quote_result__field_descriptors,
  plcontainer__quote_result__field_indices_by_name,
  1,  plcontainer__quote_result__number_ranges,
  (ProtobufCMessageInit) plcontainer__quote_result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue plcontainer__sql__sql_type__enum_values_by_number[9] =
{
  { "INVALID", "PLCONTAINER__SQL__SQL_TYPE__INVALID", 0 },
  { "STATEMENT", "PLCONTAINER__SQL__SQL_TYPE__STATEMENT", 1 },
  { "CURSOR_CLOSE", "PLCONTAINER__SQL__SQL_TYPE__CURSOR_CLOSE", 2 },
  { "FETCH", "PLCONTAINER__SQL__SQL_TYPE__FETCH", 3 },
  { "CURSOR_OPEN", "PLCONTAINER__SQL__SQL_TYPE__CURSOR_OPEN", 4 },
  { "PREPARE", "PLCONTAINER__SQL__SQL_TYPE__PREPARE", 5 },
  { "PEXECUTE", "PLCONTAINER__SQL__SQL_TYPE__PEXECUTE", 6 },
  { "UNPREPARE", "PLCONTAINER__SQL__SQL_TYPE__UNPREPARE", 7 },
  { "MAX", "PLCONTAINER__SQL__SQL_TYPE__MAX", 8 },
};
static const ProtobufCIntRange plcontainer__sql__sql_type__value_ranges[] = {
{0, 0},{0, 9}
};
static const ProtobufCEnumValueIndex plcontainer__sql__sql_type__enum_values_by_name[9] =
{
  { "CURSOR_CLOSE", 2 },
  { "CURSOR_OPEN", 4 },
  { "FETCH", 3 },
  { "INVALID", 0 },
  { "MAX", 8 },
  { "PEXECUTE", 6 },
  { "PREPARE", 5 },
  { "STATEMENT", 1 },
  { "UNPREPARE", 7 },
};
const ProtobufCEnumDescriptor plcontainer__sql__sql_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "plcontainer.SQL.SqlType",
  "SqlType",
  "Plcontainer__SQL__SqlType",
  "plcontainer",
  9,
  plcontainer__sql__sql_type__enum_values_by_number,
  9,
  plcontainer__sql__sql_type__enum_values_by_name,
  1,
  plcontainer__sql__sql_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor plcontainer__sql__field_descriptors[6] =
{
  {
    "sqltype",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Plcontainer__SQL, sqltype),
    &plcontainer__sql__sql_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "limit",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Plcontainer__SQL, limit),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "args",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Plcontainer__SQL, n_args),
    offsetof(Plcontainer__SQL, args),
    &plcontainer__argument__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pplan",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Plcontainer__SQL, pplan),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "statement",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Plcontainer__SQL, statement),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nargs",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Plcontainer__SQL, has_nargs),
    offsetof(Plcontainer__SQL, nargs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned plcontainer__sql__field_indices_by_name[] = {
  2,   /* field[2] = args */
  1,   /* field[1] = limit */
  5,   /* field[5] = nargs */
  3,   /* field[3] = pplan */
  0,   /* field[0] = sqltype */
  4,   /* field[4] = statement */
};
static const ProtobufCIntRange plcontainer__sql__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor plcontainer__sql__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "plcontainer.SQL",
  "SQL",
  "Plcontainer__SQL",
  "plcontainer",
  sizeof(Plcontainer__SQL),
  6,
  plcontainer__sql__field_descriptors,
  plcontainer__sql__field_indices_by_name,
  1,  plcontainer__sql__number_ranges,
  (ProtobufCMessageInit) plcontainer__sql__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor plcontainer__raw__field_descriptors[2] =
{
  {
    "size",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Plcontainer__Raw, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Plcontainer__Raw, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned plcontainer__raw__field_indices_by_name[] = {
  1,   /* field[1] = data */
  0,   /* field[0] = size */
};
static const ProtobufCIntRange plcontainer__raw__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor plcontainer__raw__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "plcontainer.Raw",
  "Raw",
  "Plcontainer__Raw",
  "plcontainer",
  sizeof(Plcontainer__Raw),
  2,
  plcontainer__raw__field_descriptors,
  plcontainer__raw__field_indices_by_name,
  1,  plcontainer__raw__number_ranges,
  (ProtobufCMessageInit) plcontainer__raw__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor plcontainer__subtransaction__field_descriptors[2] =
{
  {
    "action",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Plcontainer__Subtransaction, action),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Plcontainer__Subtransaction, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned plcontainer__subtransaction__field_indices_by_name[] = {
  0,   /* field[0] = action */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange plcontainer__subtransaction__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor plcontainer__subtransaction__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "plcontainer.Subtransaction",
  "Subtransaction",
  "Plcontainer__Subtransaction",
  "plcontainer",
  sizeof(Plcontainer__Subtransaction),
  2,
  plcontainer__subtransaction__field_descriptors,
  plcontainer__subtransaction__field_indices_by_name,
  1,  plcontainer__subtransaction__number_ranges,
  (ProtobufCMessageInit) plcontainer__subtransaction__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor plcontainer__subtransaction_result__field_descriptors[1] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Plcontainer__SubtransactionResult, result),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned plcontainer__subtransaction_result__field_indices_by_name[] = {
  0,   /* field[0] = result */
};
static const ProtobufCIntRange plcontainer__subtransaction_result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor plcontainer__subtransaction_result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "plcontainer.SubtransactionResult",
  "SubtransactionResult",
  "Plcontainer__SubtransactionResult",
  "plcontainer",
  sizeof(Plcontainer__SubtransactionResult),
  1,
  plcontainer__subtransaction_result__field_descriptors,
  plcontainer__subtransaction_result__field_indices_by_name,
  1,  plcontainer__subtransaction_result__number_ranges,
  (ProtobufCMessageInit) plcontainer__subtransaction_result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue plcontainer__data_type__enum_values_by_number[12] =
{
  { "INT1", "PLCONTAINER__DATA_TYPE__INT1", 0 },
  { "INT2", "PLCONTAINER__DATA_TYPE__INT2", 1 },
  { "INT4", "PLCONTAINER__DATA_TYPE__INT4", 2 },
  { "INT8", "PLCONTAINER__DATA_TYPE__INT8", 3 },
  { "FLOAT4", "PLCONTAINER__DATA_TYPE__FLOAT4", 4 },
  { "FLOAT8", "PLCONTAINER__DATA_TYPE__FLOAT8", 5 },
  { "TEXT", "PLCONTAINER__DATA_TYPE__TEXT", 6 },
  { "ARRAY", "PLCONTAINER__DATA_TYPE__ARRAY", 7 },
  { "UDT", "PLCONTAINER__DATA_TYPE__UDT", 8 },
  { "BYTEA", "PLCONTAINER__DATA_TYPE__BYTEA", 9 },
  { "INVALID", "PLCONTAINER__DATA_TYPE__INVALID", 10 },
  { "MAX", "PLCONTAINER__DATA_TYPE__MAX", 11 },
};
static const ProtobufCIntRange plcontainer__data_type__value_ranges[] = {
{0, 0},{0, 12}
};
static const ProtobufCEnumValueIndex plcontainer__data_type__enum_values_by_name[12] =
{
  { "ARRAY", 7 },
  { "BYTEA", 9 },
  { "FLOAT4", 4 },
  { "FLOAT8", 5 },
  { "INT1", 0 },
  { "INT2", 1 },
  { "INT4", 2 },
  { "INT8", 3 },
  { "INVALID", 10 },
  { "MAX", 11 },
  { "TEXT", 6 },
  { "UDT", 8 },
};
const ProtobufCEnumDescriptor plcontainer__data_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "plcontainer.DataType",
  "DataType",
  "Plcontainer__DataType",
  "plcontainer",
  12,
  plcontainer__data_type__enum_values_by_number,
  12,
  plcontainer__data_type__enum_values_by_name,
  1,
  plcontainer__data_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue plcontainer__quote_type__enum_values_by_number[3] =
{
  { "LITERAL", "PLCONTAINER__QUOTE_TYPE__LITERAL", 0 },
  { "NULLABLE", "PLCONTAINER__QUOTE_TYPE__NULLABLE", 1 },
  { "IDENT", "PLCONTAINER__QUOTE_TYPE__IDENT", 2 },
};
static const ProtobufCIntRange plcontainer__quote_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex plcontainer__quote_type__enum_values_by_name[3] =
{
  { "IDENT", 2 },
  { "LITERAL", 0 },
  { "NULLABLE", 1 },
};
const ProtobufCEnumDescriptor plcontainer__quote_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "plcontainer.QuoteType",
  "QuoteType",
  "Plcontainer__QuoteType",
  "plcontainer",
  3,
  plcontainer__quote_type__enum_values_by_number,
  3,
  plcontainer__quote_type__enum_values_by_name,
  1,
  plcontainer__quote_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
